  services:
    backend:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: savingsyogi-backend
      ports:
        - "8000:4000"
      environment:
        - REDIS_HOST=redis-server
        - REDIS_PORT=6379
      depends_on:
        - redis-server
      networks:
        - app-network

    redis-server:
      image: redis/redis-stack:latest
      container_name: redis-server
      ports:
        - "6380:6379"
      networks:
        - app-network
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

  networks:
    app-network:
      driver: bridge
